// web/src/components/ConfirmDialog.vue
<script setup lang="ts">
import { useConfirmStore } from '@/stores/confirm';
import { useI18n } from 'vue-i18n';

const confirm = useConfirmStore();
const { t } = useI18n();
</script>

<template>
  <Teleport to="body">
    <div v-if="confirm.open" class="overlay" @click.self="confirm.resolve(false)">
      <div class="dialog animate-slideUp" role="alertdialog" aria-modal="true">
        <h3 class="dialog-title">{{ confirm.options.title }}</h3>
        <p class="dialog-message">{{ confirm.options.message }}</p>
        <div class="dialog-actions">
          <button class="btn-secondary" @click="confirm.resolve(false)">
            {{ confirm.options.cancelLabel || t('common.cancel') }}
          </button>
          <button
            :class="confirm.options.danger ? 'btn-confirm-danger' : 'btn-primary'"
            @click="confirm.resolve(true)"
          >
            {{ confirm.options.confirmLabel || t('common.confirm') }}
          </button>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<style scoped>
.overlay {
  position: fixed; inset: 0; z-index: 9000;
  background: rgba(0,0,0,0.3); backdrop-filter: blur(4px);
  display: flex; align-items: center; justify-content: center;
  padding: 16px;
}
.dialog {
  background: #fff; border-radius: var(--radius-lg);
  padding: 28px; max-width: 400px; width: 100%;
  box-shadow: 0 20px 60px rgba(0,0,0,0.15);
}
.dialog-title {
  font-size: 18px; font-weight: 700; color: var(--c-txt);
  margin-bottom: 8px;
}
.dialog-message {
  font-size: 14px; color: var(--c-txt-secondary);
  line-height: 1.5; margin-bottom: 24px;
}
.dialog-actions {
  display: flex; gap: 12px; justify-content: flex-end;
}
.btn-confirm-danger {
  display: inline-flex; align-items: center; justify-content: center;
  color: #fff; font-weight: 600; padding: 10px 20px;
  border-radius: var(--radius-md); font-size: 14px;
  background: var(--c-danger);
  transition: all var(--transition);
}
.btn-confirm-danger:hover { opacity: 0.9; }
</style>

// web/src/components/ConfirmDialog.tsx
'use client';

import { createContext, useCallback, useContext, useRef, useState, type ReactNode } from 'react';
import { AlertTriangle } from 'lucide-react';

interface ConfirmOptions {
  title: string;
  message: string;
  confirmLabel?: string;
  cancelLabel?: string;
  danger?: boolean;
}

interface ConfirmContextValue {
  confirm: (opts: ConfirmOptions) => Promise<boolean>;
}

const ConfirmContext = createContext<ConfirmContextValue>({ confirm: () => Promise.resolve(false) });

export function useConfirm() {
  return useContext(ConfirmContext);
}

export function ConfirmProvider({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false);
  const [opts, setOpts] = useState<ConfirmOptions>({ title: '', message: '' });
  const resolveRef = useRef<((value: boolean) => void) | null>(null);

  const confirm = useCallback((options: ConfirmOptions) => {
    setOpts(options);
    setOpen(true);
    return new Promise<boolean>((resolve) => {
      resolveRef.current = resolve;
    });
  }, []);

  const handleConfirm = () => {
    setOpen(false);
    resolveRef.current?.(true);
    resolveRef.current = null;
  };

  const handleCancel = () => {
    setOpen(false);
    resolveRef.current?.(false);
    resolveRef.current = null;
  };

  return (
    <ConfirmContext.Provider value={{ confirm }}>
      {children}
      {open && (
        <div className="fixed inset-0 z-[90] flex items-center justify-center p-4" role="presentation">
          <div className="absolute inset-0 bg-black/30 backdrop-blur-sm" onClick={handleCancel} />
          <div
            role="alertdialog"
            aria-modal="true"
            aria-labelledby="confirm-title"
            aria-describedby="confirm-message"
            className="relative bg-white rounded-2xl shadow-xl w-full max-w-sm p-6 animate-slideUp"
          >
            <div className="flex items-start gap-3 mb-4">
              <div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${opts.danger ? 'bg-red-50' : 'bg-amber-50'}`}>
                <AlertTriangle className={`w-5 h-5 ${opts.danger ? 'text-red-500' : 'text-amber-500'}`} />
              </div>
              <div>
                <h3 id="confirm-title" className="font-bold text-txt text-base">{opts.title}</h3>
                <p id="confirm-message" className="text-sm text-txt-secondary mt-1">{opts.message}</p>
              </div>
            </div>
            <div className="flex gap-3">
              <button
                onClick={handleCancel}
                className="btn-secondary flex-1"
                autoFocus
              >
                {opts.cancelLabel || 'Cancel'}
              </button>
              <button
                onClick={handleConfirm}
                className={`flex-1 py-3 rounded-2xl text-sm font-semibold transition-all ${
                  opts.danger
                    ? 'bg-red-500 hover:bg-red-600 text-white'
                    : 'btn-primary'
                }`}
              >
                {opts.confirmLabel || 'Confirm'}
              </button>
            </div>
          </div>
        </div>
      )}
    </ConfirmContext.Provider>
  );
}
