// web/src/components/NavBar.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { PawPrint, Settings, Bell, LogOut, X, Pill, Utensils } from 'lucide-vue-next';
import { useAuthStore } from '@/stores/auth';
import { useConfirmStore } from '@/stores/confirm';

const { t } = useI18n();
const auth = useAuthStore();
const confirm = useConfirmStore();
const router = useRouter();
const route = useRoute();

const bellOpen = ref(false);
const bellRef = ref<HTMLElement | null>(null);
const notifications = ref<any[]>([]);

function closeBell(e: MouseEvent) {
  if (bellRef.value && !bellRef.value.contains(e.target as Node)) bellOpen.value = false;
}
onMounted(() => document.addEventListener('click', closeBell));
onUnmounted(() => document.removeEventListener('click', closeBell));

const links = [
  { href: '/pets', key: 'pets.myPets', icon: PawPrint },
  { href: '/settings', key: 'settings.title', icon: Settings },
];

async function handleLogout() {
  const ok = await confirm.show({
    title: t('settings.logoutTitle'),
    message: t('settings.logoutConfirm'),
    confirmLabel: t('settings.logout'),
    cancelLabel: t('common.cancel'),
  });
  if (ok) {
    auth.logout();
    router.replace('/login');
  }
}
</script>

<template>
  <nav class="navbar" role="navigation" aria-label="Main navigation">
    <div class="navbar-inner">
      <router-link to="/pets" class="navbar-brand" aria-label="PWellTrack Home">
        <div class="navbar-logo">
          <img src="/ferret-sleeping.png" alt="PWellTrack logo" width="36" height="36" />
        </div>
        <span class="navbar-title">PWellTrack</span>
      </router-link>

      <div class="navbar-actions">
        <router-link
          v-for="link in links"
          :key="link.href"
          :to="link.href"
          :class="['nav-link', { active: route.path.startsWith(link.href) }]"
          :aria-label="t(link.key)"
        >
          <component :is="link.icon" :size="16" />
          <span class="nav-link-label">{{ t(link.key) }}</span>
        </router-link>

        <div ref="bellRef" class="nav-bell-wrap">
          <button class="btn-icon" @click.stop="bellOpen = !bellOpen" :aria-label="t('settings.notifications')">
            <Bell :size="16" />
            <span v-if="notifications.length" class="bell-badge">{{ notifications.length }}</span>
          </button>
          <div v-if="bellOpen" class="bell-dropdown animate-fadeIn">
            <div class="bell-header">{{ t('settings.notifications') }}</div>
            <div v-if="!notifications.length" class="bell-empty">{{ t('settings.noNotifications') }}</div>
          </div>
        </div>

        <button class="btn-icon btn-logout" @click="handleLogout" :aria-label="t('settings.logout')">
          <LogOut :size="16" />
        </button>
      </div>
    </div>
  </nav>
</template>

<style scoped>
.navbar {
  position: sticky; top: 0; z-index: 50;
  border-bottom: 1px solid var(--c-border);
  background: rgba(255,255,255,0.8);
  backdrop-filter: blur(20px); -webkit-backdrop-filter: blur(20px);
  box-shadow: 0 4px 20px rgba(155,142,200,0.06);
}
.navbar-inner {
  max-width: 1024px; margin: 0 auto; padding: 0 16px;
  height: 56px; display: flex; align-items: center; justify-content: space-between;
}
.navbar-brand { display: flex; align-items: center; gap: 10px; }
.navbar-logo {
  width: 36px; height: 36px; border-radius: 50%; overflow: hidden;
  display: flex; align-items: center; justify-content: center;
  background: linear-gradient(135deg, #f5f0ff, #ece5ff);
}
.navbar-logo img { width: 100%; height: 100%; object-fit: contain; }
.navbar-title {
  font-weight: 700; font-size: 18px;
  background: linear-gradient(to right, #9B8EC8, #B4A5D6);
  -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;
}
@media (max-width: 640px) { .navbar-title { display: none; } }
.navbar-actions { display: flex; align-items: center; gap: 4px; }
.nav-link {
  display: flex; align-items: center; gap: 8px;
  padding: 8px 16px; border-radius: var(--radius-md); font-size: 14px; font-weight: 500;
  color: var(--c-txt-secondary); transition: all var(--transition);
}
.nav-link:hover { background: var(--c-primary-bg2); color: var(--c-primary); }
.nav-link.active { background: var(--c-primary-bg); color: var(--c-primary); box-shadow: 0 1px 3px rgba(155,142,200,0.08); }
.nav-link-label { display: none; }
@media (min-width: 640px) { .nav-link-label { display: inline; } }
.nav-bell-wrap { position: relative; }
.bell-badge {
  position: absolute; top: -2px; right: -2px;
  width: 16px; height: 16px; background: #ef4444; color: #fff;
  font-size: 10px; font-weight: 700; border-radius: 50%;
  display: flex; align-items: center; justify-content: center;
}
.bell-dropdown {
  position: absolute; right: 0; top: 100%; margin-top: 8px;
  width: 288px; background: #fff; border-radius: var(--radius-md);
  box-shadow: 0 12px 40px rgba(0,0,0,0.12); border: 1px solid #f3f4f6;
  overflow: hidden; z-index: 50;
}
.bell-header { padding: 12px 16px; border-bottom: 1px solid #f3f4f6; font-weight: 600; font-size: 14px; color: var(--c-txt); }
.bell-empty { padding: 24px 16px; text-align: center; font-size: 14px; color: var(--c-txt-muted); }
.btn-logout:hover { background: var(--c-danger-bg); color: var(--c-danger); }
</style>

// web/src/components/Navbar.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { usePathname, useRouter } from 'next/navigation';
import { useTranslation } from 'react-i18next';
import { useAuth } from '@/lib/auth';
import { useNotifications } from '@/lib/useNotifications';
import { NotificationToast } from '@/components/NotificationToast';
import { useConfirm } from '@/components/ConfirmDialog';
import { PawPrint, Settings, Bell, LogOut, X, Pill, Utensils } from 'lucide-react';

export function Navbar() {
  const { t } = useTranslation();
  const { user, logout } = useAuth();
  const pathname = usePathname();
  const router = useRouter();
  const { notifications, dismiss } = useNotifications(!!user);
  const { confirm } = useConfirm();
  const [bellOpen, setBellOpen] = useState(false);
  const bellRef = useRef<HTMLDivElement>(null);

  // Close dropdown on outside click
  useEffect(() => {
    if (!bellOpen) return;
    const handleClick = (e: MouseEvent) => {
      if (bellRef.current && !bellRef.current.contains(e.target as Node)) {
        setBellOpen(false);
      }
    };
    document.addEventListener('click', handleClick);
    return () => document.removeEventListener('click', handleClick);
  }, [bellOpen]);

  if (!user) return null;

  const links = [
    { href: '/pets', label: t('pets.myPets'), icon: PawPrint },
    { href: '/settings', label: t('settings.title'), icon: Settings },
  ];

  const handleLogout = async () => {
    const ok = await confirm({
      title: t('settings.logoutTitle'),
      message: t('settings.logoutConfirm'),
      confirmLabel: t('settings.logout'),
      cancelLabel: t('common.cancel'),
    });
    if (ok) {
      logout();
      router.replace('/login');
    }
  };

  return (
    <nav
      role="navigation"
      aria-label="Main navigation"
      className="sticky top-0 z-50 border-b border-[#f0ecff]"
      style={{ background: 'rgba(255,255,255,0.8)', backdropFilter: 'blur(20px)', WebkitBackdropFilter: 'blur(20px)', boxShadow: '0 4px 20px rgba(155,142,200,0.06)' }}
    >
      <div className="max-w-5xl mx-auto px-4 h-16 flex items-center justify-between">
        <Link href="/pets" className="flex items-center gap-2.5" aria-label="PWellTrack Home">
          <div className="w-9 h-9 rounded-full overflow-hidden flex items-center justify-center bg-gradient-to-br from-[#f5f0ff] to-[#ece5ff]">
            <Image
              src="/ferret-sleeping.png"
              alt="PWellTrack logo"
              width={36}
              height={36}
              className="w-full h-full object-contain"
            />
          </div>
          <span className="font-bold text-lg bg-gradient-to-r from-[#9B8EC8] to-[#B4A5D6] bg-clip-text text-transparent hidden sm:block">PWellTrack</span>
        </Link>

        <div className="flex items-center gap-1">
          {links.map(({ href, label, icon: Icon }) => {
            const active = pathname.startsWith(href);
            return (
              <Link
                key={href}
                href={href}
                aria-current={active ? 'page' : undefined}
                aria-label={label}
                className={`flex items-center gap-2 px-4 py-2 rounded-2xl text-sm font-medium transition-all duration-300
                  ${active ? 'bg-primary/10 text-primary shadow-sm' : 'text-txt-secondary hover:bg-primary/5 hover:text-primary'}`}
              >
                <Icon className="w-4 h-4" aria-hidden="true" />
                <span className="hidden sm:inline">{label}</span>
              </Link>
            );
          })}
          {/* Notification bell with dropdown */}
          <div ref={bellRef} className="relative">
            <button
              onClick={() => setBellOpen(v => !v)}
              className="relative p-2 rounded-xl text-txt-muted hover:bg-primary/5 hover:text-primary transition-all duration-300"
              aria-label={`${t('settings.notifications')}${notifications.length > 0 ? ` (${notifications.length})` : ''}`}
            >
              <Bell className="w-4 h-4" aria-hidden="true" />
              {notifications.length > 0 && (
                <span aria-hidden="true" className="absolute -top-0.5 -right-0.5 w-4 h-4 bg-red-500 text-white text-[10px] font-bold rounded-full flex items-center justify-center animate-fadeIn">
                  {notifications.length}
                </span>
              )}
            </button>
            {bellOpen && (
              <div className="absolute right-0 top-full mt-2 w-72 bg-white rounded-2xl shadow-xl border border-gray-100 overflow-hidden z-50 animate-fadeIn">
                <div className="px-4 py-3 border-b border-gray-100 font-semibold text-sm text-txt">{t('settings.notifications')}</div>
                {notifications.length === 0 ? (
                  <div className="px-4 py-6 text-center text-sm text-txt-muted">{t('settings.noNotifications')}</div>
                ) : (
                  <div className="max-h-64 overflow-y-auto">
                    {notifications.map(n => (
                      <div key={n.id} className="flex items-start gap-2.5 px-4 py-3 border-b border-gray-50 last:border-0 hover:bg-gray-50/50 transition-colors">
                        <div className={`w-7 h-7 rounded-lg flex items-center justify-center shrink-0 mt-0.5 ${n.type === 'medication_reminder' ? 'bg-purple-50' : 'bg-orange-50'}`}>
                          {n.type === 'medication_reminder'
                            ? <Pill className="w-3.5 h-3.5 text-purple-500" />
                            : <Utensils className="w-3.5 h-3.5 text-orange-500" />}
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium text-txt">{n.pet_name}</p>
                          <p className="text-xs text-txt-muted truncate">
                            {n.type === 'medication_reminder'
                              ? `${n.medication_name} (${n.dosage})`
                              : t('notifications.feedingReminder')}
                          </p>
                        </div>
                        <button onClick={() => dismiss(n.id)} className="p-0.5 rounded-md hover:bg-gray-100 transition-colors shrink-0">
                          <X className="w-3.5 h-3.5 text-txt-muted" />
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
          <button
            onClick={handleLogout}
            className="ml-1 p-2 rounded-xl text-txt-muted hover:bg-red-50 hover:text-red-500 transition-all duration-300"
            aria-label={t('settings.logout')}
          >
            <LogOut className="w-4 h-4" aria-hidden="true" />
          </button>
        </div>
      </div>
      <NotificationToast notifications={notifications} onDismiss={dismiss} />
    </nav>
  );
}
