// web/src/components/PetAvatar.tsx
'use client';

import { useState } from 'react';
import { resolvePhotoUrl } from '@/lib/photos';

const SPECIES_COLORS: Record<string, string> = {
  dog: 'from-orange-400 to-amber-300',
  cat: 'from-primary to-primary-light',
  exotic: 'from-emerald-400 to-green-300',
  other: 'from-sky-400 to-teal-300',
};

interface Props {
  name: string;
  species: string;
  photoUrl?: string;
  size?: 'sm' | 'md' | 'lg';
}

const sizes = { sm: 'w-10 h-10 text-sm', md: 'w-14 h-14 text-lg', lg: 'w-20 h-20 text-2xl' };

export function PetAvatar({ name, species, photoUrl, size = 'md' }: Props) {
  const [imgError, setImgError] = useState(false);
  const initials = name.slice(0, 2).toUpperCase();
  const gradient = SPECIES_COLORS[species] || SPECIES_COLORS.exotic;
  const src = resolvePhotoUrl(photoUrl);

  const fallback = (
    <div className={`${sizes[size]} rounded-2xl bg-gradient-to-br ${gradient} flex items-center justify-center font-bold text-white shadow-sm`}>
      {initials}
    </div>
  );

  if (src && !imgError) {
    return (
      <img
        src={src}
        alt={name}
        className={`${sizes[size]} rounded-2xl object-cover`}
        onError={() => setImgError(true)}
      />
    );
  }

  return fallback;
}

// web/src/components/PetAvatar.vue
<script setup lang="ts">
import { ref } from 'vue';
import { PawPrint, Cat, Rabbit } from 'lucide-vue-next';
import { resolvePhotoUrl } from '@/lib/photos';

const props = withDefaults(defineProps<{
  photoUrl?: string | null;
  name: string;
  species?: string;
  size?: number;
}>(), {
  size: 48,
});

const photoError = ref(false);
const resolved = resolvePhotoUrl(props.photoUrl);
const iconSize = Math.round(props.size * 0.5);
</script>

<template>
  <div class="pet-avatar" :style="{ width: size + 'px', height: size + 'px' }">
    <img
      v-if="resolved && !photoError"
      :src="resolved"
      :alt="name"
      class="pet-avatar-img"
      @error="photoError = true"
    />
    <div v-else class="pet-avatar-fallback">
      <Cat v-if="species === 'cat'" :size="iconSize" />
      <Rabbit v-else-if="species === 'exotic'" :size="iconSize" />
      <PawPrint v-else :size="iconSize" />
    </div>
  </div>
</template>

<style scoped>
.pet-avatar {
  border-radius: 50%; overflow: hidden; flex-shrink: 0;
}
.pet-avatar-img {
  width: 100%; height: 100%; object-fit: cover;
}
.pet-avatar-fallback {
  width: 100%; height: 100%;
  background: linear-gradient(135deg, #f5f0ff, #ece5ff);
  display: flex; align-items: center; justify-content: center;
  color: var(--c-primary);
}
</style>
