// web/src/components/RecordPage.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { ArrowLeft, Plus, Trash2 } from 'lucide-vue-next';
import { petsApi } from '@/lib/api';
import { useToastStore } from '@/stores/toast';
import { useConfirmStore } from '@/stores/confirm';
import type { Pet } from '@/lib/types';
import EmptyState from '@/components/EmptyState.vue';
import AppModal from '@/components/AppModal.vue';

const props = defineProps<{
  title: string;
  emptyTitle: string;
  emptySubtitle: string;
  deleteMsg: string;
  savedMsg: string;
  modalTitle: string;
  fetchFn: (petId: number) => Promise<any[]>;
  deleteFn: (id: number) => Promise<void>;
  createFn: (petId: number, data: any) => Promise<any>;
  updateFn?: (id: number, data: any) => Promise<any>;
}>();

const { t } = useI18n();
const route = useRoute();
const router = useRouter();
const toast = useToastStore();
const confirm = useConfirmStore();

const petId = Number(route.params.petId);
const pet = ref<Pet | null>(null);
const items = ref<any[]>([]);
const loading = ref(true);
const showModal = ref(false);
const editingItem = ref<any>(null);
const deleting = ref(false);

async function fetchData() {
  if (!Number.isFinite(petId) || petId <= 0) {
    router.push('/pets');
    return;
  }
  try {
    const [p, data] = await Promise.all([
      petsApi.get(petId),
      props.fetchFn(petId),
    ]);
    pet.value = p;
    items.value = data;
  } catch (e) {
    console.warn('[RecordPage] Failed to fetch:', e instanceof Error ? e.message : e);
  }
  loading.value = false;
}

onMounted(fetchData);

async function handleDelete(item: any) {
  if (deleting.value) return;
  const ok = await confirm.show({
    title: t('common.delete'),
    message: props.deleteMsg,
    confirmLabel: t('common.delete'),
    danger: true,
  });
  if (!ok) return;
  deleting.value = true;
  try {
    await props.deleteFn(item.id);
    await fetchData();
  } catch (e: any) {
    toast.show(e.message, 'error');
  } finally {
    deleting.value = false;
  }
}

function openAdd() {
  editingItem.value = null;
  showModal.value = true;
}

function openEdit(item: any) {
  editingItem.value = item;
  showModal.value = true;
}

async function handleSaved() {
  toast.show(props.savedMsg, 'success');
  showModal.value = false;
  editingItem.value = null;
  await fetchData();
}

defineExpose({ petId, pet, items, loading, showModal, editingItem, openAdd, openEdit, handleDelete, handleSaved, fetchData });
</script>

<template>
  <main class="container" style="padding-top: 24px; padding-bottom: 48px;">
    <button class="back-btn" @click="router.push(`/pets/${petId}`)">
      <ArrowLeft :size="18" />
      <span v-if="pet">{{ pet.name }}</span>
    </button>

    <div class="record-header">
      <h1 class="page-title">{{ title }}</h1>
      <button class="btn-primary" @click="openAdd">
        <Plus :size="16" /> {{ t('common.add') }}
      </button>
    </div>

    <div v-if="loading" class="loading-center"><div class="spinner" /></div>

    <EmptyState v-else-if="!items.length" :title="emptyTitle" :subtitle="emptySubtitle" />

    <div v-else class="record-list">
      <slot name="list" :items="items" :on-delete="handleDelete" :on-edit="openEdit" />
    </div>

    <AppModal v-if="showModal" :title="modalTitle" @close="showModal = false">
      <slot name="form" :pet-id="petId" :editing="editingItem" :on-saved="handleSaved" />
    </AppModal>
  </main>
</template>

<style scoped>
.back-btn {
  display: inline-flex; align-items: center; gap: 6px;
  font-size: 14px; font-weight: 500; color: var(--c-primary);
  margin-bottom: 16px; padding: 6px 0;
}
.back-btn:hover { opacity: 0.8; }
.record-header {
  display: flex; align-items: center; justify-content: space-between;
  margin-bottom: 20px;
}
.page-title { font-size: 24px; font-weight: 700; color: var(--c-txt); }
.record-list { display: flex; flex-direction: column; gap: 10px; }
</style>

// web/src/components/RecordPage.tsx
'use client';

import { useEffect, useState, type ReactNode } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useTranslation } from 'react-i18next';
import { useAuth } from '@/lib/auth';
import { petsApi } from '@/lib/api';
import { Navbar } from '@/components/Navbar';
import { EmptyState } from '@/components/EmptyState';
import { Modal } from '@/components/Modal';
import { ArrowLeft, Plus, Pencil, Trash2, X, AlertTriangle, RefreshCw } from 'lucide-react';
import { useToast } from '@/components/Toast';
import { useConfirm } from '@/components/ConfirmDialog';
import type { Pet } from '@/lib/types';

interface Props<T> {
  title: string;
  emptyText: string;
  addLabel: string;
  icon: ReactNode;
  listFn: (petId: number, dateFrom?: string, dateTo?: string) => Promise<T[]>;
  deleteFn: (id: number) => Promise<void>;
  updateFn?: (id: number, data: any) => Promise<T>;
  renderItem: (item: T, t: any) => ReactNode;
  renderForm: (opts: {
    onSave: () => void;
    petId: number;
    t: any;
    editingItem?: T;
  }) => ReactNode;
  supportsDateFilter?: boolean;
}

export function RecordPage<T extends { id: number }>({
  title, emptyText, addLabel, icon, listFn, deleteFn, updateFn, renderItem, renderForm, supportsDateFilter,
}: Props<T>) {
  const { t } = useTranslation();
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();
  const params = useParams();
  const petId = Number(params.petId);
  const { toast } = useToast();
  const { confirm } = useConfirm();

  const [pet, setPet] = useState<Pet | null>(null);
  const [items, setItems] = useState<T[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [editingItem, setEditingItem] = useState<T | null>(null);
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');

  useEffect(() => {
    if (!authLoading && !user) router.replace('/login');
  }, [user, authLoading, router]);

  const load = async () => {
    setError('');
    setLoading(true);
    try {
      const [p, list] = await Promise.all([
        petsApi.get(petId),
        listFn(petId, dateFrom || undefined, dateTo || undefined),
      ]);
      setPet(p);
      setItems(list);
    } catch (err: any) {
      setError(err.message || t('common.error'));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { if (user && petId) load(); }, [user, petId, dateFrom, dateTo]);

  const handleDelete = async (id: number) => {
    const ok = await confirm({
      title: t('common.deleteTitle'),
      message: t('common.deleteMessage'),
      confirmLabel: t('common.delete'),
      cancelLabel: t('common.cancel'),
      danger: true,
    });
    if (!ok) return;
    try {
      await deleteFn(id);
      setItems(prev => prev.filter(i => i.id !== id));
      toast(t('common.deleted'));
    } catch (err: any) {
      setError(err.message || t('common.error'));
    }
  };

  const openEdit = (item: T) => {
    setEditingItem(item);
    setShowForm(true);
  };

  const closeForm = () => {
    setShowForm(false);
    setEditingItem(null);
  };

  if (authLoading || loading) {
    return (
      <>
        <Navbar />
        <div className="flex items-center justify-center h-[60vh]">
          <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin" />
        </div>
      </>
    );
  }

  if (error && !pet) {
    return (
      <>
        <Navbar />
        <main className="max-w-3xl mx-auto px-4 py-6">
          <button onClick={() => router.push('/pets')} className="flex items-center gap-1 text-sm text-txt-secondary hover:text-primary mb-4">
            <ArrowLeft className="w-4 h-4" /> {t('pets.myPets')}
          </button>
          <div className="card text-center py-10">
            <AlertTriangle className="w-10 h-10 text-red-400 mx-auto mb-3" />
            <p className="text-txt-secondary mb-4">{error}</p>
            <button onClick={load} className="btn-primary inline-flex items-center gap-2">
              <RefreshCw className="w-4 h-4" />
              {t('common.retry')}
            </button>
          </div>
        </main>
      </>
    );
  }

  return (
    <>
      <Navbar />
      <main className="max-w-3xl mx-auto px-4 py-6">
        <button onClick={() => router.push(`/pets/${petId}`)} className="flex items-center gap-1 text-sm text-txt-secondary hover:text-primary mb-4">
          <ArrowLeft className="w-4 h-4" /> {pet?.name || '...'}
        </button>

        <div className="flex items-center justify-between mb-4">
          <h1 className="text-2xl font-bold text-txt">{title}</h1>
          <button onClick={() => { setEditingItem(null); setShowForm(true); }} className="btn-primary flex items-center gap-2">
            <Plus className="w-4 h-4" />
            {addLabel}
          </button>
        </div>

        {supportsDateFilter && (
          <div className="flex gap-3 mb-4">
            <div className="flex-1">
              <label className="text-xs text-txt-muted block mb-1">{t('common.dateFrom')}</label>
              <input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)} className="input" />
            </div>
            <div className="flex-1">
              <label className="text-xs text-txt-muted block mb-1">{t('common.dateTo')}</label>
              <input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)} className="input" />
            </div>
            {(dateFrom || dateTo) && (
              <button onClick={() => { setDateFrom(''); setDateTo(''); }} className="self-end p-2.5 rounded-xl border border-gray-200 hover:bg-gray-50 transition-colors">
                <X className="w-4 h-4 text-txt-muted" />
              </button>
            )}
          </div>
        )}

        {error && (
          <div className="mb-4 bg-red-50/80 border border-red-100 text-red-500 px-3.5 py-2.5 rounded-2xl text-sm font-medium">
            {error}
          </div>
        )}

        {items.length === 0 ? (
          <EmptyState icon={icon} title={emptyText} />
        ) : (
          <div className="space-y-3">
            {items.map(item => (
              <div key={item.id} className="card flex items-start gap-3">
                <div className="flex-1">{renderItem(item, t)}</div>
                <div className="flex gap-1 shrink-0 mt-0.5">
                  {updateFn && (
                    <button onClick={() => openEdit(item)} className="p-1.5 rounded-xl text-primary/60 hover:bg-primary/5 hover:text-primary transition-all">
                      <Pencil className="w-4 h-4" />
                    </button>
                  )}
                  <button onClick={() => handleDelete(item.id)} className="btn-danger shrink-0">
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}

        <Modal open={showForm} onClose={closeForm} title={editingItem ? t('common.edit') : addLabel}>
          {renderForm({
            petId,
            t,
            onSave: () => { closeForm(); load(); toast(t('common.saved')); },
            editingItem: editingItem ?? undefined,
          })}
        </Modal>
      </main>
    </>
  );
}
